# Generated by Django 4.2 on 2025-03-17 05:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_device_id_transaction_ip_address_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_user_id_f5864b_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='session_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'), message='Minimum amount is ₹1'), django.core.validators.MaxValueValidator(Decimal('100000.00'), message='Maximum amount is ₹1,00,000')]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
