# Generated by Django 4.2 on 2025-03-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_transaction_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
