# Generated by Django 4.2 on 2025-03-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_is_suspicious_transaction_sender_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='suspicious_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
