# Generated by Django 4.2 on 2025-03-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_transaction_suspicious_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ml_risk_score',
            field=models.IntegerField(blank=True, help_text='ML model risk score percentage (0-100)', null=True),
        ),
    ]
